const Array=[
    {
        id:1,
        image:"https://cdn.europosters.eu/image/750/posters/stranger-things-one-sheet-season-2-i67844.jpg",
        title:"Stranger Things",
        About:"",
        link:"https://www.netflix.com/pk/title/80057281",
    },
    {
        id:2,
        image:"https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3Mzk1ZWZjXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_FMjpg_UX1000_.jpg",
        title:"Sandman",
        About:"",
        link:"https://www.netflix.com/pk/title/81150303",
    },{
        id:3,
        image:"https://m.media-amazon.com/images/M/MV5BNTc5OGU1YjItZmVhZi00NmE3LTk0ZWEtZDE1OGJjMTMzNDY2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
        title:"The MidNight club",
        About:"",
        link:"https://www.imdb.com/title/tt13444912/?ref_=tt_mv_close",
    },{
        id:4,
        image:"https://www.tvguide.com/a/img/catalog/provider/1/1/1-8898459552.jpg",
        title:"Breath Into The Shadow",
        About:"",
        link:"",
    },
    {
        id:1,
        image:"https://cdn.europosters.eu/image/750/posters/stranger-things-one-sheet-season-2-i67844.jpg",
        title:"Stranger Things",
        About:"",
        link:"https://www.netflix.com/pk/title/80057281",
    },
    {
        id:2,
        image:"https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3Mzk1ZWZjXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_FMjpg_UX1000_.jpg",
        title:"Sandman",
        About:"",
        link:"https://www.netflix.com/pk/title/81150303",
    },{
        id:3,
        image:"https://m.media-amazon.com/images/M/MV5BNTc5OGU1YjItZmVhZi00NmE3LTk0ZWEtZDE1OGJjMTMzNDY2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
        title:"The MidNight club",
        About:"",
        link:"https://www.imdb.com/title/tt13444912/?ref_=tt_mv_close",
    },{
        id:4,
        image:"https://www.tvguide.com/a/img/catalog/provider/1/1/1-8898459552.jpg",
        title:"Breath Into The Shadow",
        About:"",
        link:"",
    },
    {
        id:1,
        image:"https://cdn.europosters.eu/image/750/posters/stranger-things-one-sheet-season-2-i67844.jpg",
        title:"Stranger Things",
        About:"",
        link:"https://www.netflix.com/pk/title/80057281",
    },
    {
        id:2,
        image:"https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3Mzk1ZWZjXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_FMjpg_UX1000_.jpg",
        title:"Sandman",
        About:"",
        link:"https://www.netflix.com/pk/title/81150303",
    },{
        id:3,
        image:"https://m.media-amazon.com/images/M/MV5BNTc5OGU1YjItZmVhZi00NmE3LTk0ZWEtZDE1OGJjMTMzNDY2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
        title:"The MidNight club",
        About:"",
        link:"https://www.imdb.com/title/tt13444912/?ref_=tt_mv_close",
    },{
        id:4,
        image:"https://www.tvguide.com/a/img/catalog/provider/1/1/1-8898459552.jpg",
        title:"Breath Into The Shadow",
        About:"",
        link:"",
    },
    {
        id:1,
        image:"https://cdn.europosters.eu/image/750/posters/stranger-things-one-sheet-season-2-i67844.jpg",
        title:"Stranger Things",
        About:"",
        link:"https://www.netflix.com/pk/title/80057281",
    },
    {
        id:2,
        image:"https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3Mzk1ZWZjXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_FMjpg_UX1000_.jpg",
        title:"Sandman",
        About:"",
        link:"https://www.netflix.com/pk/title/81150303",
    },{
        id:3,
        image:"https://m.media-amazon.com/images/M/MV5BNTc5OGU1YjItZmVhZi00NmE3LTk0ZWEtZDE1OGJjMTMzNDY2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
        title:"The MidNight club",
        About:"",
        link:"https://www.imdb.com/title/tt13444912/?ref_=tt_mv_close",
    },{
        id:4,
        image:"https://www.tvguide.com/a/img/catalog/provider/1/1/1-8898459552.jpg",
        title:"Breath Into The Shadow",
        About:"",
        link:"",
    },
    {
        id:1,
        image:"https://cdn.europosters.eu/image/750/posters/stranger-things-one-sheet-season-2-i67844.jpg",
        title:"Stranger Things",
        About:"",
        link:"https://www.netflix.com/pk/title/80057281",
    },
    {
        id:2,
        image:"https://m.media-amazon.com/images/M/MV5BYTM0NjZjYjItM2JiYS00NmU5LWJmMTMtZjQ0OWU3Mzk1ZWZjXkEyXkFqcGdeQXVyMTAxNDE3MTE5._V1_FMjpg_UX1000_.jpg",
        title:"Sandman",
        About:"",
        link:"https://www.netflix.com/pk/title/81150303",
    },{
        id:3,
        image:"https://m.media-amazon.com/images/M/MV5BNTc5OGU1YjItZmVhZi00NmE3LTk0ZWEtZDE1OGJjMTMzNDY2XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_FMjpg_UX1000_.jpg",
        title:"The MidNight club",
        About:"",
        link:"https://www.imdb.com/title/tt13444912/?ref_=tt_mv_close",
    },{
        id:4,
        image:"https://www.tvguide.com/a/img/catalog/provider/1/1/1-8898459552.jpg",
        title:"Breath Into The Shadow",
        About:"",
        link:"",
    },
 ]
export default Array;
